-- 1. Profiles Table (Extends Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    username TEXT,
    role TEXT DEFAULT 'customer',
    address TEXT,
    phone TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add role column if it doesn't exist (for existing tables)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'role') THEN
        ALTER TABLE public.profiles ADD COLUMN role TEXT DEFAULT 'customer';
    END IF;
END $$;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
-- Safely handle policies (drop before create to update)
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
    DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
END $$;
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Sync Trigger (Create profile on Signup)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (new.id, new.raw_user_meta_data->>'username');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 3. Pizzas Table
CREATE TABLE IF NOT EXISTS public.pizzas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    "unitPrice" NUMERIC NOT NULL,
    ingredients TEXT[] NOT NULL,
    "soldOut" BOOLEAN DEFAULT FALSE,
    "imageUrl" TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE SET NULL,
    customer TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    address TEXT NOT NULL,
    priority BOOLEAN DEFAULT FALSE,
    "orderPrice" NUMERIC,
    "priorityPrice" NUMERIC,
    status TEXT DEFAULT 'preparing',
    "paymentStatus" TEXT DEFAULT 'pending',
    cart JSONB NOT NULL,
    "estimatedDelivery" TIMESTAMP WITH TIME ZONE DEFAULT (now() + interval '45 minutes'),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Full Menu Data (Working URLs) - Prices in NGN
INSERT INTO public.pizzas (id, name, "unitPrice", ingredients, "soldOut", "imageUrl")
VALUES
(1, 'Margherita', 3500, '{tomato,mozzarella,basil}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-1.jpg'),
(2, 'Capricciosa', 4200, '{tomato,mozzarella,ham,mushrooms,artichoke}', true, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-2.jpg'),
(3, 'Romana', 4500, '{tomato,mozzarella,prosciutto}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-3.jpg'),
(4, 'Prosciutto e Rucola', 4800, '{tomato,mozzarella,prosciutto,arugula}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-4.jpg'),
(5, 'Diavola', 4800, '{tomato,mozzarella,spicy salami,chili flakes}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-5.jpg'),
(6, 'Vegetale', 3800, '{tomato,mozzarella,bell peppers,onions,mushrooms}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-6.jpg'),
(7, 'Napoli', 4800, '{tomato,mozzarella,fresh tomato,basil}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-7.jpg'),
(8, 'Siciliana', 4800, '{tomato,mozzarella,anchovies,olives,capers}', true, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-8.jpg'),
(9, 'Pepperoni', 4200, '{tomato,mozzarella,pepperoni}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-9.jpg'),
(10, 'Hawaiian', 4500, '{tomato,mozzarella,pineapple,ham}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-10.jpg'),
(11, 'Spinach and Mushroom', 4500, '{tomato,mozzarella,spinach,mushrooms}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-11.jpg'),
(12, 'Mediterranean', 4800, '{tomato,mozzarella,sun-dried tomatoes,olives,artichoke}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-12.jpg'),
(13, 'Greek', 4800, '{tomato,mozzarella,spinach,feta,olives,pepperoncini}', true, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-13.jpg'),
(14, 'Abruzzese', 4800, '{tomato,mozzarella,prosciutto,arugula}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-14.jpg'),
(15, 'Pesto Chicken', 4800, '{pesto,mozzarella,chicken,sun-dried tomatoes,spinach}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-15.jpg'),
(16, 'Eggplant Parmesan', 4500, '{marinara,mozzarella,eggplant,parmesan}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-16.jpg'),
(17, 'Roasted Veggie', 4500, '{marinara,mozzarella,zucchini,eggplant,peppers,onions}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-17.jpg'),
(18, 'Tofu and Mushroom', 4500, '{marinara,mozzarella,tofu,mushrooms,bell peppers}', false, 'https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-18.jpg')
ON CONFLICT (id) DO UPDATE SET "unitPrice" = EXCLUDED."unitPrice", "imageUrl" = EXCLUDED."imageUrl";

-- 6. Enable RLS (Row Level Security)
ALTER TABLE public.pizzas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 7. Public Access Policies
DO $$
BEGIN
    DROP POLICY IF EXISTS "Public can view menu" ON public.pizzas;
    DROP POLICY IF EXISTS "Anyone can create order" ON public.orders;
    DROP POLICY IF EXISTS "Users can view own orders" ON public.orders;
    DROP POLICY IF EXISTS "Users can update own orders" ON public.orders;
    DROP POLICY IF EXISTS "Admins can view all orders" ON public.orders;
    DROP POLICY IF EXISTS "Admins can update all orders" ON public.orders;
END $$;

CREATE POLICY "Public can view menu" ON public.pizzas FOR SELECT USING (true);
CREATE POLICY "Anyone can create order" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can view own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);
CREATE POLICY "Users can update own orders" ON public.orders FOR UPDATE USING (auth.uid() = user_id);

-- Admin policies (check role from profiles table)
CREATE POLICY "Admins can view all orders" ON public.orders FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins can update all orders" ON public.orders FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
